# Generated by Django 6.1 on 2026-09-07 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screener', '0002_job_alter_screeningresult_job_delete_jobdescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, help_text='Optional candidate name (extracted in subsequent phases)', max_length=255)),
                ('candidate_email', models.CharField(blank=True, help_text='Optional candidate email (extracted in subsequent phases)', max_length=255)),
                ('file', models.FileField(help_text='Uploaded PDF resume file', upload_to='resumes/%Y/%m/')),
                ('extracted_text', models.TextField(blank=True, help_text='Raw text extracted from the PDF via pypdf')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, help_text='Job posting this resume was submitted for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='screener.job')),
                ('recruiter', models.ForeignKey(help_text='Recruiter who uploaded and owns this resume', on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
