# Generated by Django 6.1 on 2026-09-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('review', 'In Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='review', help_text="Recruiter review status. Every newly screened resume starts strictly as 'review'.", max_length=20),
        ),
    ]
