# Generated by Django 6.1 on 2026-09-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='recruiter_notes',
            field=models.TextField(blank=True, default='', help_text='Notes written by recruiter'),
        ),
    ]
