# Generated by Django 6.1 on 2026-09-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('raw_text', models.TextField(blank=True, help_text='Raw parsed text extracted from the resume PDF')),
                ('status', models.CharField(choices=[('review', 'In Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='review', help_text="Recruiter decision status. Always starts at 'review'.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(help_text='Full text of the job description')),
                ('required_skills', models.JSONField(blank=True, default=list, help_text="List of mandatory skills (e.g. ['Python', 'Django', 'PostgreSQL'])")),
                ('preferred_skills', models.JSONField(blank=True, default=list, help_text="List of nice-to-have skills (e.g. ['Docker', 'AWS', 'Redis'])")),
                ('min_experience_years', models.FloatField(default=0.0, help_text='Minimum required years of professional experience')),
                ('required_education', models.CharField(blank=True, help_text="Required education degree or discipline (e.g. Bachelor's in Computer Science)", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Description',
                'verbose_name_plural': 'Job Descriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_required_skills', models.JSONField(blank=True, default=list, help_text='Required skills present in candidate resume')),
                ('missing_required_skills', models.JSONField(blank=True, default=list, help_text='Required skills absent from candidate resume')),
                ('matched_preferred_skills', models.JSONField(blank=True, default=list, help_text='Preferred skills present in candidate resume')),
                ('missing_preferred_skills', models.JSONField(blank=True, default=list, help_text='Preferred skills absent from candidate resume')),
                ('candidate_experience_years', models.FloatField(default=0.0, help_text='Extracted total years of experience')),
                ('candidate_education', models.CharField(blank=True, help_text='Extracted education credentials', max_length=255)),
                ('candidate_projects_summary', models.TextField(blank=True, help_text='Summary of relevant projects extracted from resume')),
                ('required_skills_score', models.FloatField(default=0.0, help_text='Deterministic score for required skills (0.0 to 40.0)')),
                ('preferred_skills_score', models.FloatField(default=0.0, help_text='Deterministic score for preferred skills (0.0 to 15.0)')),
                ('experience_score', models.FloatField(default=0.0, help_text='Deterministic score for experience match (0.0 to 20.0)')),
                ('education_score', models.FloatField(default=0.0, help_text='Deterministic score for education match (0.0 to 10.0)')),
                ('projects_score', models.FloatField(default=0.0, help_text='Deterministic score for projects match (0.0 to 15.0)')),
                ('total_score', models.FloatField(default=0.0, help_text='Final deterministic total score (0.0 to 100.0)')),
                ('candidate_summary', models.TextField(blank=True, help_text='Short narrative summary generated by the LLM')),
                ('screened_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='screener.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='screener.jobdescription')),
            ],
            options={
                'verbose_name': 'Screening Result',
                'verbose_name_plural': 'Screening Results',
                'ordering': ['-total_score', '-screened_at'],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
