# Generated by Django 6.1 on 2026-09-07 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the job role and responsibilities')),
                ('required_skills', models.JSONField(blank=True, default=list, help_text="List of mandatory required skills (e.g. ['Python', 'Django', 'PostgreSQL'])")),
                ('preferred_skills', models.JSONField(blank=True, default=list, help_text="List of preferred nice-to-have skills (e.g. ['Docker', 'AWS', 'Redis'])")),
                ('min_experience', models.FloatField(default=0.0, help_text='Minimum years of professional experience required')),
                ('max_experience', models.FloatField(blank=True, help_text='Maximum years of professional experience (optional)', null=True)),
                ('minimum_score', models.FloatField(blank=True, help_text='Optional threshold qualification score (0-100)', null=True)),
                ('shortlist_count', models.PositiveIntegerField(blank=True, help_text='Optional maximum number of candidates to shortlist', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', help_text='Job posting status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(help_text='Recruiter owner of this job posting', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='screeningresult',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='screener.job'),
        ),
        migrations.DeleteModel(
            name='JobDescription',
        ),
    ]
