# Generated by Django 6.1 on 2026-09-07 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        ('screener', '0002_job_alter_screeningresult_job_delete_jobdescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screeningresult',
            options={'ordering': ['-screened_at'], 'verbose_name': 'Screening Result', 'verbose_name_plural': 'Screening Results'},
        ),
        migrations.AlterUniqueTogether(
            name='screeningresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='candidate_education_json',
            field=models.JSONField(blank=True, default=list, help_text="Structured education list [{'degree': ..., 'field': ...}]"),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='candidate_projects_json',
            field=models.JSONField(blank=True, default=list, help_text="Structured projects list [{'name': ..., 'description': ...}]"),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='raw_ai_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Raw structured JSON response returned by LLM'),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='resume',
            field=models.ForeignKey(blank=True, help_text='Resume associated with this screening result', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='resumes.resume'),
        ),
        migrations.AlterField(
            model_name='screeningresult',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='screener.candidate'),
        ),
        migrations.AlterField(
            model_name='screeningresult',
            name='candidate_education',
            field=models.CharField(blank=True, help_text='Extracted education credentials summary string', max_length=255),
        ),
    ]
