# Generated by Django 6.1 on 2026-09-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0003_alter_screeningresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningresult',
            name='recruiter_notes',
            field=models.TextField(blank=True, default='', help_text='Recruiter evaluation notes and comments'),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='status',
            field=models.CharField(choices=[('review', 'In Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='review', help_text='Recruiter decision status: review, shortlisted, rejected', max_length=20),
        ),
    ]
