# Generated by Django 6.1 on 2026-09-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0004_screeningresult_recruiter_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningresult',
            name='candidate',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
