# Generated by Django 6.1.1 on 2026-10-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0005_remove_screeningresult_candidate_delete_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningresult',
            name='candidate_education',
            field=models.TextField(blank=True, help_text='Extracted education credentials summary string'),
        ),
    ]
