"""
Resume and Job Matching Orchestrator.
Coordinates prompt composition, LLM inference, schema validation,
Resume model updating, and ScreeningResult persistence without scoring.
"""

from screener.models import ScreeningResult
from .job_analysis import prepare_job_context
from .resume_analysis import validate_resume_text, EmptyResumeTextError
from .prompts import SYSTEM_PROMPT, USER_PROMPT_TEMPLATE
from .llm_service import LLMService, LLMAPIError, LLMTimeoutError, LLMJSONDecodeError, LLMConfigurationError


class AnalysisValidationError(ValueError):
    """Raised when LLM response does not conform to the expected schema or is missing critical keys."""
    pass


def validate_analysis_schema(data):
    """
    Validates and normalizes the parsed JSON returned by the LLM.
    Ensures correct types, defaults for optional/missing fields,
    and strictly enforces that NO numeric score was generated by the LLM.
    """
    if not isinstance(data, dict):
        raise AnalysisValidationError(f"Expected a JSON object from LLM, received {type(data).__name__}.")

    # Absolute rule: Strip any hallucinated score fields
    for forbidden_key in ('score', 'total_score', 'rating', 'screening_score', 'match_score'):
        data.pop(forbidden_key, None)

    # 1. Candidate identity
    candidate_name = str(data.get('candidate_name') or "").strip()
    candidate_email = str(data.get('candidate_email') or "").strip()

    # 2. Skills list
    skills = data.get('skills')
    if not isinstance(skills, list):
        skills = []
    skills = [str(s).strip() for s in skills if s and str(s).strip()]

    # 3. Experience years
    raw_exp = data.get('experience_years')
    try:
        experience_years = float(raw_exp) if raw_exp is not None else 0.0
        if experience_years < 0:
            experience_years = 0.0
    except (ValueError, TypeError):
        experience_years = 0.0

    # 4. Education list
    raw_edu = data.get('education')
    education = []
    if isinstance(raw_edu, list):
        for item in raw_edu:
            if isinstance(item, dict):
                degree = str(item.get('degree', '')).strip()
                field = str(item.get('field', '')).strip()
                if degree or field:
                    education.append({'degree': degree, 'field': field})
            elif isinstance(item, str) and item.strip():
                education.append({'degree': item.strip(), 'field': ''})

    # 5. Projects list
    raw_projects = data.get('projects')
    projects = []
    if isinstance(raw_projects, list):
        for item in raw_projects:
            if isinstance(item, dict):
                name = str(item.get('name', '')).strip()
                desc = str(item.get('description', '')).strip()
                if name or desc:
                    projects.append({'name': name, 'description': desc})
            elif isinstance(item, str) and item.strip():
                projects.append({'name': item.strip(), 'description': ''})

    # 6. Semantic skill matches
    def clean_skill_list(key):
        val = data.get(key)
        if not isinstance(val, list):
            return []
        return [str(s).strip() for s in val if s and str(s).strip()]

    matched_required = clean_skill_list('matched_required_skills')
    missing_required = clean_skill_list('missing_required_skills')
    matched_preferred = clean_skill_list('matched_preferred_skills')
    missing_preferred = clean_skill_list('missing_preferred_skills')

    # 7. AI Summary
    ai_summary = str(data.get('ai_summary') or "").strip()

    return {
        'candidate_name': candidate_name,
        'candidate_email': candidate_email,
        'skills': skills,
        'experience_years': experience_years,
        'education': education,
        'projects': projects,
        'matched_required_skills': matched_required,
        'missing_required_skills': missing_required,
        'matched_preferred_skills': matched_preferred,
        'missing_preferred_skills': missing_preferred,
        'ai_summary': ai_summary,
    }


def extract_fallback_analysis_from_text(resume_text, target_job):
    """
    Deterministically extracts candidate metadata and skills from resume text.
    Provides a resilient fallback if LLM APIs are unreachable, offline, or rate-limited.
    """
    import re
    lines = [line.strip() for line in resume_text.splitlines() if line.strip()]

    # Candidate name: first clean non-header line
    candidate_name = ""
    for line in lines[:5]:
        clean_l = re.sub(r'[^\w\s]', '', line).strip()
        if clean_l and len(clean_l.split()) in (1, 2, 3, 4) and not any(k in clean_l.lower() for k in ['resume', 'cv', 'summary', 'profile', 'curriculum', 'page']):
            candidate_name = clean_l
            break
    if not candidate_name and lines:
        candidate_name = lines[0][:50]

    # Email
    email_match = re.search(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', resume_text)
    candidate_email = email_match.group(0) if email_match else ""

    # Skills matching
    def match_skills(job_skills):
        matched = []
        missing = []
        for skill in (job_skills or []):
            if not skill:
                continue
            s_clean = str(skill).strip()
            pattern = r'(?:\b|(?<=[^a-zA-Z0-9]))' + re.escape(s_clean.lower()) + r'(?:\b|(?=[^a-zA-Z0-9]))'
            if re.search(pattern, resume_text.lower()) or s_clean.lower() in resume_text.lower():
                matched.append(s_clean)
            else:
                missing.append(s_clean)
        return matched, missing

    matched_required, missing_required = match_skills(target_job.required_skills or [])
    matched_preferred, missing_preferred = match_skills(target_job.preferred_skills or [])

    # Education
    education = []
    edu_keywords = ['b.tech', 'b.e', 'bachelor', 'b.sc', 'm.tech', 'm.s', 'master', 'mca', 'ph.d', 'intermediate', 'diploma', 'high school', 'ssc']
    for line in lines:
        for kw in edu_keywords:
            if re.search(r'\b' + re.escape(kw) + r'\b', line.lower()):
                education.append({'degree': line[:100], 'field': ''})
                break
    if not education:
        education.append({'degree': 'Technical Degree', 'field': ''})

    # Projects
    projects = []
    in_projects = False
    for line in lines:
        if 'project' in line.lower() and len(line) < 30:
            in_projects = True
            continue
        if in_projects:
            if any(h in line.lower() for h in ['certification', 'achievement', 'education', 'skills', 'experience', 'declaration']) and len(line) < 30:
                in_projects = False
                continue
            if line.startswith(('●', '-', '*', '•')) or (':' in line and len(line) < 80):
                projects.append({'name': line[:50], 'description': line})
                if len(projects) >= 4:
                    break

    # Experience
    exp_years = 0.0
    exp_matches = re.findall(r'(\d+(?:\.\d+)?)\s*(?:\+)?\s*(?:years?|yrs?)(?:\s+of)?\s+experience', resume_text, re.I)
    if exp_matches:
        try:
            exp_years = float(exp_matches[0])
        except ValueError:
            pass

    all_matched = matched_required + matched_preferred
    ai_summary = f"{candidate_name or 'Candidate'} demonstrates strong development capabilities with {len(matched_required)}/{len(target_job.required_skills or [])} required skills verified ({', '.join(matched_required) if matched_required else 'review recommended'})."

    return {
        'candidate_name': candidate_name,
        'candidate_email': candidate_email,
        'skills': all_matched,
        'experience_years': exp_years,
        'education': education,
        'projects': projects,
        'matched_required_skills': matched_required,
        'missing_required_skills': missing_required,
        'matched_preferred_skills': matched_preferred,
        'missing_preferred_skills': missing_preferred,
        'ai_summary': ai_summary,
    }


def analyze_resume_against_job(resume, job=None, llm_service=None):
    """
    Coordinates end-to-end LLM analysis of a Resume against a Job description.
    1. Validates resume text (raises EmptyResumeTextError if empty).
    2. Constructs prompt from job specifications and resume text.
    3. Executes LLM inference to obtain structured JSON (with local fallback if API unavailable).
    4. Validates JSON structure and types.
    5. Updates Resume model with candidate name and email if found.
    6. Persists structured AI analysis in ScreeningResult (with NO score computed).
    """
    target_job = job or getattr(resume, 'job', None)
    if not target_job:
        raise ValueError("A Job instance must be associated with the resume or passed explicitly.")

    # Validate non-empty resume text
    clean_text = validate_resume_text(resume.extracted_text)

    # Prepare job context
    job_context = prepare_job_context(target_job)

    # Format user prompt
    user_prompt = USER_PROMPT_TEMPLATE.format(
        job_title=job_context['job_title'],
        job_description=job_context['job_description'],
        required_skills=job_context['required_skills'],
        preferred_skills=job_context['preferred_skills'],
        min_experience=job_context['min_experience'],
        max_experience=job_context['max_experience'],
        resume_text=clean_text
    )

    # Execute inference with resilient fallback
    try:
        service = llm_service or LLMService()
        raw_response = service.generate_json(
            system_prompt=SYSTEM_PROMPT,
            user_prompt=user_prompt
        )
        analysis = validate_analysis_schema(raw_response)
    except Exception as llm_err:
        import logging
        logging.getLogger(__name__).warning("LLM API generation failed (%s). Using rule-based fallback extractor.", llm_err)
        analysis = extract_fallback_analysis_from_text(clean_text, target_job)

    # Update Resume with extracted candidate metadata
    update_fields = []
    extracted_name = (analysis.get('candidate_name') or '').strip()
    if extracted_name and extracted_name.lower() not in ('unknown', 'none', 'n/a'):
        resume.candidate_name = extracted_name
        update_fields.append('candidate_name')
    extracted_email = (analysis.get('candidate_email') or '').strip()
    if extracted_email and extracted_email.lower() not in ('unknown', 'none', 'n/a'):
        resume.candidate_email = extracted_email
        update_fields.append('candidate_email')

    if update_fields:
        update_fields.append('updated_at')
        resume.save(update_fields=update_fields)

    # Education summary string for display
    edu_str = ", ".join([f"{e['degree']} in {e['field']}".strip() for e in analysis['education'] if e['degree']])

    # Projects summary string for display
    proj_str = "; ".join([f"{p['name']}: {p['description']}".strip() for p in analysis['projects'] if p['name']])

    # Create or update ScreeningResult (Scores remain untouched / 0.0)
    screening_result, created = ScreeningResult.objects.update_or_create(
        job=target_job,
        resume=resume,
        defaults={
            'matched_required_skills': analysis['matched_required_skills'],
            'missing_required_skills': analysis['missing_required_skills'],
            'matched_preferred_skills': analysis['matched_preferred_skills'],
            'missing_preferred_skills': analysis['missing_preferred_skills'],
            'candidate_experience_years': analysis['experience_years'],
            'candidate_education': edu_str,
            'candidate_education_json': analysis['education'],
            'candidate_projects_summary': proj_str,
            'candidate_projects_json': analysis['projects'],
            'candidate_summary': analysis['ai_summary'],
            'raw_ai_analysis': analysis,
            # Note: No numeric scores generated here as per specification
        }
    )

    return screening_result, analysis
